import type { AgentMobileSettings } from '../services/agentApi';

// Valori di partenza del pannello Setup, usati finche' il backend non risponde.
// Stanno in un file proprio: esportarli da AgentTab.tsx romperebbe il
// ricaricamento rapido, che pretende file di soli componenti.
export const defaultSettings: AgentMobileSettings = {
  mode: 'conservative',
  markets_enabled: 'both',
  execution_mode: 'dry_run',
  network: 'testnet',
  test_scaling_pct: 10,
  operating_hours_utc: '00:00-23:59',
  drawdown_alert_enabled: true,
  daily_loss_limit_pct: -8,
  drawdown_cap_pct: -15,
  min_pool_liquidity_usd: 50000,
  market_reversal_filter_enabled: true,
  spot_market_reversal_filter_enabled: true,
  perp_market_reversal_filter_enabled: false,
  spot_breakeven_enabled: true,
  perp_breakeven_enabled: true,
  spot_trailing_enabled: true,
  perp_trailing_enabled: true,
  spot_time_stop_enabled: false,
  perp_time_stop_enabled: false,
  perp_trend_shock_enabled: true,
  perp_trend_shock_adx_threshold: 25,
  perp_trend_shock_natr_percentile: 90,
  perp_trend_shock_volume_threshold: 2.0,
  perp_trend_shock_recovery_confirmations: 3,
  perp_smart_sl_enabled: true,
  perp_smart_sl_l1_frac: 0.333,
  perp_smart_sl_l2_frac: 0.666,
  perp_smart_sl_split_l1: 0.25,
  perp_smart_sl_split_l2: 0.55,
  perp_smart_sl_split_l3: 0.20,
  perp_smart_sl_rebuy_mode: 'above_entry',
  perp_smart_sl_rebuy_above_entry_pct: 100,
  perp_smart_sl_split_l1_r2: 0.75,
  perp_smart_sl_split_l2_r2: 0.20,
  perp_smart_sl_split_l3_r2: 0.05,
  perp_smart_sl_delta_l1: 0.08,
  perp_smart_sl_delta_l2: 0.16,
  perp_smart_sl_confirmation_candles: 2,
  perp_smart_sl_max_reentries: 1,
  perp_smart_sl_tp_adjust_after_rebuy: true,
  perp_smart_sl_tp_recovery_delta_pct: 7,
  spot_breakeven_mode: 'atr' as const,
  perp_breakeven_mode: 'atr' as const,
  spot_sl_mode: 'atr' as const,
  perp_sl_mode: 'atr' as const,
  spot_structural_stop_lookback_candles: 20,
  spot_structural_stop_buffer_pct: 1.10,
  perp_structural_stop_lookback_candles: 20,
  perp_structural_stop_buffer_pct: 1.10,
  perp_min_rr: 1.2,
  perp_tp1_atr_multiplier: 2.5,
  perp_tp2_atr_multiplier: 4.0,
  spot_capital_per_trade_pct: 6,
  spot_per_trade_pct: 1.5,
  spot_max_open_positions: 3,
  spot_max_exposure_pct: 30,
  spot_cooldown_minutes: 30,
  spot_max_slippage_pct: 1,
  perp_capital_per_trade_pct: 4,
  perp_per_trade_pct: 1.5,
  perp_max_open_positions: 5,
  perp_max_exposure_pct: 20,
  perp_cooldown_minutes: 15,
  perp_max_slippage_pct: 0.5,
  perp_fixed_margin_enabled: false,
  perp_fixed_margin_usd: 50,
  capital_per_trade_pct: 6,
  per_trade_pct: 1.5,
  max_open_positions: 3,
  max_total_exposure_pct: 30,
  max_slippage_pct: 1,
  cooldown_minutes: 30,
  spot_confidence_threshold: 0.7,
  spot_volatility_trigger_pct: 3,
  spot_relative_volume_threshold: 1.8,
  spot_atr_stop_multiplier: 1.5,
  spot_trailing_distance_pct: 2,
  spot_partial_take_profit_pct: 50,
  spot_tp1_close_pct: 50,
  spot_time_stop_hours: 6,
  perp_direction_mode: 'long_short',
  perp_min_leverage: 4,
  perp_max_leverage: 40,
  perp_value_area_pct: 68,
  perp_atr_stop_multiplier: 0.8,
  perp_trailing_mode: 'largo' as const,
  perp_trailing_pnl_pct: 0,
  perp_protection_mode: 'trailing' as const,
  perp_profit_lock_steps: [[0.5, 0.25], [0.7, 0.5], [0.95, 0.8]] as Array<[number, number]>,
  perp_ratchet_breakeven_pct: 50,
  perp_ratchet_breakeven_after_step: 3,
  perp_ratchet_run_beyond_tp2: true,
  perp_ratchet_trailing_pct: 1,
  perp_breakeven_min_profit_usd: 0,
  perp_tp1_close_pct: 70,
  perp_time_stop_hours: 8,
  perp_fee_mode: 'taker' as const,
  spot_fee_mode: 'all' as const,
  post_close_candles: 10,
  chart_pre_open_candles: 20,
};
